/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Telas;


import controllers.UsuarioController;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author renan
 */
public class TelaListaUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListaUsuarios
     */
    public TelaListaUsuarios() {
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) jtbUsuarios.getModel();
        jtbUsuarios.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
    
    public void readTable(){
         DefaultTableModel modelo = (DefaultTableModel) jtbUsuarios.getModel();
         UsuarioController usuario = new UsuarioController();
         modelo.setNumRows(0);
         usuario.listar().forEach((user) -> {
             modelo.addRow(new Object[]{
                 user.getNome(),
                 user.getMatricula(),
                 user.getSexo(),
                 user.getCpf(),
                 user.getTelefone(),
                 user.getEmail(),
                 user.getCelular(),
                 user.getNascimento().toString()
                 
             });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();

        setClosable(true);

        jtbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matricula", "Sexo", "Cpf", "Telefone", "Email", "Celular", "Data de Nascimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbUsuarios;
    // End of variables declaration//GEN-END:variables
}
