/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.Telas;

import controllers.ServicosController;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author renan
 */
public class TelaListaEmprestimos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaListaEmprestimos
     */
    public TelaListaEmprestimos() {
        initComponents();
      DefaultTableModel modelo = (DefaultTableModel) jtbEmprestimos.getModel();
        jtbEmprestimos.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
    
    public void readTable(){
         DefaultTableModel modelo = (DefaultTableModel) jtbEmprestimos.getModel();
         ServicosController servicos = new ServicosController();
         modelo.setNumRows(0);
         servicos.listaEmprestimos().forEach((emp) -> {
             modelo.addRow(new Object[]{
                 emp.getLivro().getTitulo(),
                 emp.getUsuario().getNome(),
                 emp.getData_emprestimo().toString(),
                 emp.getData_devolucao().toString()
             });
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbEmprestimos = new javax.swing.JTable();

        setClosable(true);

        jScrollPane1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jtbEmprestimos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtbEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo do Livro", "Usuario", "Data de Empréstimo", "Data de Devolução"
            }
        ));
        jScrollPane1.setViewportView(jtbEmprestimos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbEmprestimos;
    // End of variables declaration//GEN-END:variables
}
